service: ${env:APP_NAME}
frameworkVersion: '3'

useDotenv: true

configValidationMode: warn

deprecationNotificationMode: warn:summary

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${env:ENVIRONMENT, 'dev'}
  stackName: ${self:service}-${self:provider.stage}
  region: ${env:AWS_REGION, 'us-east-1'}
  eventBridge:
    useCloudFormation: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter*
          Resource:
            - arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/${self:provider.stage}/${self:service}
            - arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/${self:provider.stage}/${self:service}/*
  timeout: 15
  environment: ${self:custom.envByStage.${self:provider.stage}}

plugins:
  - ./deploy/plugins/serverless-run-remote-migrations/index.js
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

custom:
  httpPort: ${env:HTTP_PORT, 3000}
  socketPort: ${env:SOCKET_PORT, 3001}
  serverless-offline:
    httpPort: ${self:custom.httpPort}
  # API Domain Configuration
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    stage: $default
    basePath: ''
    certificateArn: ${env:AWS_ACM_CERTIFICATE_ARN}
    createRoute53Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: http
    autoDomain: true
  envByStage:
    dev:
      APP_NAME: ${self:service}
      LOG_LEVEL: ${env:LOG_LEVEL, 'debug'}
      STAGE: ${self:provider.stage}
      LOCALSTACK_ENDPOINT: http://localhost:4567
    prod:
      APP_NAME: ${self:service}
      LOG_LEVEL: ${env:LOG_LEVEL, 'debug'}
      STAGE: ${self:provider.stage}
  serverless-run-remote-migrations:
    build:
      dockerfile: ./deploy/migrations.Dockerfile
      context: .
      tag: ${env:COMMIT_SHA, 'latest'}
    deploy:
      # cpu: 512
      # memory: 1024
      command:
        - npm
        - run
        - db:migrate:deploy
      aws:
        stackName: ${self:service}-${self:provider.stage}-db-migrations
        secret:
          name: DATABASE_URL
          valueFrom: arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/app/${self:provider.stage}/${self:service}/DATABASE_URL
  webpack:
    includeModules: true

functions:
  app:
    handler: src/index.handler
    events:
      - httpApi: '*'
    package:
      include:
        - src/client/dist
